### ISSUE TITLE
how to use this? how to run

### ISSUE THREAD

**Issue by johnson7788** [etcd-io/dbtester#361]
Sorry, i am newbie, thank you very much!
how to use this? how to run?

**Comment by johnson7788** [comment]
2017-11-01 17:50:09.861463 W | agent: cannot get disk device mounted at '/' (expected 1 df row at "/" (got []))
2017-11-01 17:50:09.943888 W | control: cannot get disk device mounted at '/' (expected 1 df row at "/" (got []))
2017-11-01 17:50:09.948614 I | analyze: reading system metrics data for etcd__tip
Error: open 2017Q2-01-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-tip-go1.8.3-1-server-system-metrics-interpolated.csv: no such file or directory
Usage:
  dbtester analyze [flags]

Flags:
  -c, --config string   YAML configuration file path.

open 2017Q2-01-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-tip-go1.8.3-1-server-system-metrics-interpolated.csv: no such file or directory

**Comment by johnson7788** [comment]
Hi, superman
In the config.yaml, where i can specify the zookeeper ip address, are  peer_ips  the agent address? thanks!

**Comment by gyuho** [comment]
Yeah. We've only tested in Google Cloud VMs. Please let me know if you need any other help.

**Comment by gengjia007** [comment]
Can you send me the Complete building steps？
